set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(TOOL_CHAIN /opt/toolchain/OpenWrt-SDK-15.05-mvebu_gcc-4.8-linaro_uClibc-0.9.33.2_eabi.Linux-x86_64/staging_dir)

set(CMAKE_SYSROOT ${TOOL_CHAIN}/target-arm_cortex-a9+vfpv3_uClibc-0.9.33.2_eabi)
set(COMPILER_PREFIX ${TOOL_CHAIN}/toolchain-arm_cortex-a9+vfpv3_gcc-4.8-linaro_uClibc-0.9.33.2_eabi/bin/arm-openwrt-linux-)
set(TOOLCHAIN_FILE "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_CURRENT_LIST_FILE}")

#set(CMAKE_INSTALL_PREFIX ${CMAKE_SYSROOT})
set(CMAKE_AR ${COMPILER_PREFIX}ar CACHE FILEPATH  "Archiver")
set(CMAKE_C_COMPILER ${COMPILER_PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${COMPILER_PREFIX}g++)
set(CMAKE_C_FLAGS_INIT "-DOTA_PLATFORM_ICM")
set(CMAKE_CXX_FLAGS_INIT "-DOTA_PLATFORM_ICM")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(USE_SYS_ZLIB OFF CACHE BOOL "Use system in-bluild ZLIB")
set(USE_SYS_SSL OFF CACHE BOOL "Use system in-bluild SSL")
set(USE_STATIC_CRYPTO ON CACHE BOOL "Use static crypto library")
